apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-config
  namespace: codeserver
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: codeserver-137.184.250.184.nip.io
  PUID: "0"
  PGID: "0"

