volumes:
  data-vol:
networks:
  mynet:
services:
  mydb:
    image:  stackupiss/northwind-db:v1
    volumes:
    - data-vol:/var/lib/mysql
    networks:
    - mynet
  myapp:
    image: stackupiss/northwind-app:v1
    environment:
    - DB_HOST=mydb
    - DB_USER=root
    - DB_PASSWORD=changeit
    networks:
    - mynet
    ports:
    - 8080:3000
    depends_on:
      - mydb