apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: minio-ns
data:
  MINIO_ROOT_USER: Admin
  MINIO_DATA_DIR: /data
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: minio-sts-{0...3}.minio-svc-headless.minio-ns.svc.cluster.local/data
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"